a = input('число один: ')
b = input('число два: ')
print(a, '+', b, '=', a+b, sep='')
a = int(a)
b = int(b)
print(a, '+', b, '=', a+b, sep='')
a = float(a)
b = float(b)
print(a, '+', b, '=', a+b, sep='')
a = int(a)
b = float(b)
print(a, '+', b, '=', a+b, sep='')
