# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import Qt, QTimer
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 300)
        self.minutes = QtWidgets.QLCDNumber(Dialog)
        self.minutes.setGeometry(QtCore.QRect(0, 0, 100, 100))
        self.minutes.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(238, 238, 236);")
        self.minutes.setDigitCount(2)
        self.minutes.setProperty("intValue", 99)
        self.minutes.setObjectName("minutes")
        self.Mseconds = QtWidgets.QLCDNumber(Dialog)
        self.Mseconds.setGeometry(QtCore.QRect(200, 0, 100, 100))
        self.Mseconds.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(238, 238, 236);")
        self.Mseconds.setDigitCount(4)
        self.Mseconds.setProperty("intValue", 1000)
        self.Mseconds.setObjectName("Mseconds")
        self.seconds = QtWidgets.QLCDNumber(Dialog)
        self.seconds.setGeometry(QtCore.QRect(100, 0, 100, 100))
        self.seconds.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(238, 238, 236);")
        self.seconds.setDigitCount(2)
        self.seconds.setProperty("intValue", 60)
        self.seconds.setObjectName("seconds")
        self.Button = QtWidgets.QPushButton(Dialog)
        self.Button.setGeometry(QtCore.QRect(0, 200, 300, 100))
        self.Button.setStyleSheet("color: rgb(238, 238, 236);\n"
"background-color: rgb(164, 0, 0);")
        self.Button.setObjectName("Button")
        self.back = QtWidgets.QPushButton(Dialog)
        self.back.setGeometry(QtCore.QRect(0, 100, 300, 100))
        self.back.setStyleSheet("color: rgb(238, 238, 236);\n"
"background-color: rgb(164, 0, 0);")
        self.back.setObjectName("back")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.application()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "stop watch"))
        self.Button.setText(_translate("Dialog", "start"))
        self.back.setText(_translate("Dialog", "back"))
        Dialog.setWindowIcon(QIcon('icon.png'))

    def application(self):
        self.Button.clicked.connect(lambda: self.sClick(self.Button.text()))
        self.Mseconds.display(0)
        self.seconds.display(0)
        self.minutes.display(0)

    def sClick(self,value):
        self.qtimer = QTimer()
        self.qtimer.timeout.connect(lambda: self.sClick('start'))
        self.qtimer.setSingleShot(True)
        if value == 'start':
            self.Button.setText('stop')
            lcd_value = self.Mseconds.value()
            if lcd_value < 999:
                self.Mseconds.display(lcd_value + 1)
                self.qtimer.start(1)
            else:
                if self.seconds.value() < 59:
                    self.seconds.display(self.seconds.value() + 1)
                else:
                    self.seconds.display(0)
                    if self.minutes.value() < 98:
                        self.minutes.display(self.minutes.value()+1)
                    else:
                        self.minutes.display(0)
                self.Mseconds.display(0)
                self.sClick('start')
                self.Button.clicked.connect(lambda: self.sClick(self.Button.text()))
        else:
            self.qtimer.stop()
            self.Button.setText('start')




